### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by Exlonk** [jvalegre/robert#47]
![image](https://github.com/user-attachments/assets/41f78eb9-2972-4bd5-bae7-d3a399919b74)

Is this a bug? or I did something wrong?

the command was "python -m robert --aqme --ignore "[Solvent]" --y "Q" --csv_name" file_name

**Comment by ddgunizar** [comment]
Hello Exlonk. Thank you for reporting this. 

Could you specify exactly the command line used? It seems like there might be some unusual character in the name of your CSV.

**Comment by Exlonk** [comment]
I think that the problem was that I was working near to the root folder, so when I change the directory, the problem was fix

**Comment by Exlonk** [comment]
Your module is great by the way

**Comment by ddgunizar** [comment]
Thank you for the feedback! If you have any other questions or find a bug, please don’t hesitate to let us know.

**Comment by ddgunizar** [comment]
Thank you for the feedback! If you have any other questions or find a bug, please don’t hesitate to let us know.
